# Generated by Django 2.1.7 on 2019-04-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='detail',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='fruit',
            old_name='mileage',
            new_name='price',
        ),
    ]
