# Generated by Django 2.1.7 on 2019-03-01 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='mileage',
            new_name='weight',
        ),
    ]
